version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: my_postgres_db  
    restart: unless-stopped        
    ports:
      - "6000:5432"
    environment:
      POSTGRES_USER: mydv
      POSTGRES_PASSWORD: mydb
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
